version: "3.7"

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: moheatp_pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      heatp_moh:
        ipv4_address: 192.168.17.2

  rstudio:
    image: rocker/rstudio:latest
    container_name: moheatp_rstudio
    ports:
      - "8789:8787"
    environment:
      USER: rstudio
      PASSWORD: rstudio_password
    volumes:
      - ./app/rstudio:/home/rstudio
    networks:
      heatp_moh:
        ipv4_address: 192.168.17.3

  shiny:
    container_name: moheatp_shinydhis2
    build:
      context: ./app/shiny
      dockerfile: Dockerfile.shiny
    ports:
      - "3838:3838"
    environment:
      USER: shiny
      PASSWORD: shiny_password
    volumes:
      - ./app/shiny:/srv/shiny-server
    networks:
      heatp_moh:
        ipv4_address: 192.168.17.4

  windows:
    image: dockurr/windows
    container_name: moheatp_windows
    environment:
      VERSION: "win11"
      RAM_SIZE: "4G"
      CPU_CORES: "4"
      DISK_SIZE: "64G"
      USERNAME: "heatplus"
      PASSWORD: "heatplus"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 8912:8912
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
    volumes:
      - ./app:/shared
    networks:
      heatp_moh:
        ipv4_address: 192.168.17.5

volumes:
  pgadmin_data: {}

networks:
  heatp_moh:
    ipam:
      driver: default
      config:
        - subnet: 192.168.17.0/24
